spring:
  application.name: hhp-clean-architecture
  h2:
    console:
      enabled: true  # H2 콘솔을 사용할 수 있게 설정
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb  # 'testdb'는 원하는 이름으로 설정 가능
#    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create  # 스키마 자동 업데이트
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true # SQL 쿼리 출력 여부
        format_sql: true # SQL 쿼리 포맷팅 여부

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html