spring:
#  config:
#    activate:
#      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialects: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    database: mysql
    generate-ddl: true
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true # 데이터 베이스 초기화 시점을 지연

  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:sql/data.sql

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    server: localhost:9092
    topic:
      reservation: reservation_success
    consumer:
      auto-offset-reset: earliest
      reservation:
        group-id: reservation_consumer

logging:
  level:
    root: ERROR
    io:
      hhplus:
        concert:
          app:
            infra:
              spring: INFO # 해당 패키지로 지정